version: "3"

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  up:
    cmds:
      - docker compose up -d

  down:
    cmds:
      - docker compose down

  rebuild:
    cmds:
      - docker compose down
      - docker compose build --no-cache
      - docker compose up -d

  shell:
    cmds:
      - docker compose exec browser-dev bash

  logs:
    cmds:
      - docker compose logs -f

  dev:
    cmds:
      - task: up
      - task: run:watch

  update-refs:
    cmds:
      - git submodule update --remote

  # ---------------------------
  # Lint
  # ---------------------------
  lint:
    desc: Run all lint checks
    cmds:
      - task lint:yaml
      - task lint:rust

  lint:yaml:
    cmds:
      - docker run --rm -v {{.PWD}}:/work giantswarm/yamllint .

  lint:rust:
    cmds:
      - docker compose exec -T browser-dev cargo fmt --all -- --check
      - >-
        docker compose exec -T browser-dev cargo clippy
        --workspace  --exclude ui_wasabi -- -D warnings

  # ---------------------------
  # Test
  # ---------------------------
  test:
    cmds:
      - >-
        docker compose exec -T browser-dev cargo test
        --workspace  --exclude ui_wasabi

  before-commit:
    cmds:
      - task lint
      - task test

  # ---------------------------
  # Run
  # ---------------------------
  run:
    cmds:
      - >-
        docker compose exec -T browser-dev cargo run
        --workspace

  run:watch:
    cmds:
      - >-
        docker compose exec -T browser-dev cargo watch
        -x "run --workspace"
